refactoring
veselv2010/VkBatchPhotoUploader pull request #1
Opened 2020-04-21 08:53 UTC by veselv2010

2020-04-21 09:21 UTC, moetelo requested changes
![image](https://psv4.userapi.com/c848220/u529010804/docs/d6/7780f689e69b/fb26aacabb05bbcc1a390.gif?extra=EH6ibZTcxZOpuFvI-V02wEhZVbQEm5svEkbRLQxrHOlSiYoGst8bk21sQ3JmuCrXltfHIUPM68w6hoMoRqGa8E42rNvCWMyeezzISYO71npc8hP-THL11VNKO-hBa4ImladyL6f6dasHjeuCRjmF)

время пошло

2020-04-21 09:21 UTC, moetelo commented on VkBatchPhotoUploader/ConsoleDialogManager.cs
> +        public void DisplayAlbumRequest(VkCollection<PhotoAlbum> albums)
`ICollection<PhotoAlbum>` может быть?
твоему методу пофигу, какая именно это коллекция. главное, что у неё есть индексатор и что она хранит в себе PhotoAlbum

2020-04-21 09:21 UTC, moetelo commented on VkBatchPhotoUploader/ConsoleDialogManager.cs
> +            Console.Write("code = ");
```cs
public string AskCode() // ReadCode()? или ещё как нибудь
{
    Console.Write("code = ");
    return Console.ReadLine();
```

или что-нибудь такое было бы уместнее

2020-04-21 09:21 UTC, moetelo commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        public VkApi api { get; }
`private/protected VkApi api;`

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/ConsoleDialogManager.cs
> +        public void DisplayAlbumRequest(VkCollection<PhotoAlbum> albums)
лучше `DisplayAlbumInfo`

```cs
Console.BackgroundColor = 0;
Console.Write("# of desired album: ");
```
а вот эти последниие две строки вынести в отдельный `AskAlbum()` (или как нибудь так)

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        public VkAuthenticator(ConsoleDialogManager consoleDialog)
`VkAuthenticator` не должен ничего знать про способ вывода
Вывод может быть разным, например, консольный, или в винформах можно что-нибудь нарисовать, или в впфе что-нибудь, или в юнити.

Пусть это будет просто класс, который занимается аутентификацией и ничем более.

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +                using (this.api = new VkApi())
Убери эти юзинги, вынеси их создание в конструктор и в приватные поля класса

А класс `VkAuthenticator` пусть реализует `IDisposable`.
Таким образом, ты будешь писать `using (var authenticator = new VkAuthenticator()) { ... }`, а внутреннее задиспозится само

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +                    var resp = client.SendAsync(request).Result;
Вот ты и напоролся. Конструктор-то не может быть асинхронным, и правда!
Пусть этот класс принимает в себя `client_id, `client_secret` и `redirect_uri`
И у него будет отдельный метод `Task<string> AuthorizeAsync()`, который будет возвращать токен.

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +            var progressBar = new ProgressBar();
`using var progressBar`

2020-04-21 09:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +            string url = "https://oauth.vk.com/authorize?client_id=7096347&display=page&scope=photos&redirect_uri=http://blank.org/&response_type=code&v=5.103";
Пусть этот класс принимает в себя `client_id, `client_secret` и `redirect_uri`

и генерирует эту строку из этих приватных полей

2020-04-21 09:24 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +                    var resp = client.SendAsync(request).Result;
кроме того, этот класс не будет ничего знать о `VkApi`

2020-04-21 09:30 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +            string url = "https://oauth.vk.com/authorize?client_id=7096347&display=page&scope=photos&redirect_uri=http://blank.org/&response_type=code&v=5.103";
ещё лучше:

пусть этот класс принимает объект `VkAppSettings`, у которого будут эти поля

2020-04-21 10:40 UTC, moetelo requested changes

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAppSettings.cs
> +    public class VkAppSettings
```cs
public VkAppSettings(string clientId, string clientSecret, string redirectUri)
{
    this.ClientId = clientId;
    this.ClientSecret = clientSecret;
    this.RedirectUri = redirectUri;
}
```

и этот объект уже будешь передавать куда надо

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAppSettings.cs
> +    public class VkAppSettings
пусть это будет не набор констант, а просто класс-контейнер для настроек вк апи

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/ConsoleDialogManager.cs
> +            foreach(var album in albums)
раз у тебя `IList`, ты теперь можешь использовать `albums[someIndex]` без проблем в цикле for

а так у тебя `albums.IndexOf` тяжёлая операция

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +            await api.AuthorizeAsync(new ApiAuthParams
выпилить. пусть этот метод возвращает `accessToken` просто, а `AuthorizeAsync` происходит в другом месте

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/Program.cs
> +            var vkAppSettings = new VkAppSettings();
`new VkAppSettings("clientId", "secret", "uri");` соответственно тут будет с учётом правки конструктора

2020-04-21 10:40 UTC, Shifu462 commented on VkBatchPhotoUploader/Program.cs
> +        static void Main()
а что с `async static Task Main()` не срослось?

2020-04-21 12:26 UTC, veselv2010 commented on VkBatchPhotoUploader/Program.cs
> +        static void Main()
с ним не работает `FolderBrowserDialog`

2020-04-21 13:19 UTC, moetelo requested changes

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        async public Task<VkApi> GetAuthorizedApiAsync(string accessToken)
Это мне нравится! Это хороший подход.

Сделай так, чтобы этот метод возвращал каждый раз новый экземпляр `VkApi`, иначе могут возникнуть непредвиденные последствия.

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        async public Task<VkApi> GetAuthorizedApiAsync(string accessToken)
Соответственно, приватное поле можно выпилить из этого класса.

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAppSettings.cs
> +        public string redirectUri { get; }
что за кодстайл? почему проперти мелкобуквенные?
обычно поля с мелкой буквы пишутся, а проперти с заглавной

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/Program.cs
> +        static void Main()
понял

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/Program.cs
> +        static void Main()
потом нужно будет разобраться, как-то пофиксить
возможно, нужно открывать `FolderBrowserDialog` в отдельном потоке или что-нибудь такое. не знаю.
https://stackoverflow.com/a/35025951/5512932

2020-04-21 13:19 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        async public Task<VkApi> GetAuthorizedApiAsync(string accessToken)
Причём пусть этот метод возвращает не `Task<VkApi>`, а `Task<IVkApi>`

2020-04-21 13:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAppSettings.cs
> +        public string redirectUri { get; }
ну это конечно придирка но всё же
какой-нибудь потенциальный работодатель зайдёт, не по себе станет, наверное

2020-04-21 13:21 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAppSettings.cs
> +        public string redirectUri { get; }
типа всё равно что в шлёпанцах прийти на собеседование (я приходил)

2020-04-21 13:30 UTC, moetelo requested changes

2020-04-21 13:30 UTC, Shifu462 commented on VkBatchPhotoUploader/ConsoleDialogManager.cs
> +                Console.Write(" name: " + albums[i].Title);
я думаю, можно в начале цикла сделать
`var album = albums[i];`

и юзать уже этот `album`, не ломая пальцы о квадратные скобки

2020-04-21 13:30 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +        public VkPhotoUploader(VkApi api, ConsoleDialogManager dialogManager)
VkPhotoUploader не должен знать ничего про пользовательский интерфейс.
пусть в нём будет логика только про аплод фото и ничего более

2020-04-21 13:30 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +        private VkApi api { get; }
`private IVkApi api;`

2020-04-21 13:30 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +        public VkPhotoUploader(VkApi api, ConsoleDialogManager dialogManager)
`IVkApi api`
пусть он принимает интерфейс и не знает ничего о конкретной реализации!

2020-04-21 13:40 UTC, moetelo requested changes

2020-04-21 13:40 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +        private long AlbumSelector(VkApi api)
пусть методы этого класса юзают `this.api`, а не `api` из аргументов методов

2020-04-21 13:49 UTC, moetelo requested changes
в конструкторах не должно быть логики

2020-04-21 13:49 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +            string url = $"https://oauth.vk.com/authorize?client_id={settings.clientId}&" +
запрещено! нельзя!
в конструкторе не должно быть никакой логики!

всё, что после этой строчки нужно вынести в отдельный метод, который ты будешь дёргать из Program (или откуда-нибудь ещё)

2020-04-21 13:49 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +            this.files = GetFolderFiles();
запрещено! нельзя! [1]
в конструкторе не должно быть никакой логики!

2020-04-22 21:31 UTC, moetelo requested changes

2020-04-22 21:31 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +            var tokenParamsDict = new Dictionary<string, string>
это можно извлечь чтобы такой дикшенари создавался в методе `AppSettings.ToDictionary()`

2020-04-22 21:34 UTC, moetelo requested changes

2020-04-22 21:34 UTC, Shifu462 commented on VkBatchPhotoUploader/VkPhotoUploader.cs
> +        private IVkApi api { get; }
их незачем делать автопропертями!
`private readonly IVkApi api;`

2020-04-22 21:34 UTC, Shifu462 commented on VkBatchPhotoUploader/VkAuthenticator.cs
> +        private VkAppSettings settings { get; }
из всех сделать ридонли-поля

2020-04-22 22:16 UTC, merged